# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ip2location_ruby 8.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "ip2location_ruby"
  s.version = "8.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Vincent.Z"]
  s.date = "2016-07-25"
  s.description = "The official IP2Location Ruby library to geolocate an IP address. You can lookup for country, region, city, latitude, longitude, zip code, time zone, ISP, domain, area code, usage type, mobile data, weather data and elevation from an IP address. Supported both IPv4 and IPv6 lookup."
  s.email = "support@ip2location.com"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Rakefile",
    "VERSION",
    "ip2location_ruby.gemspec",
    "lib/ip2location_ruby.rb",
    "lib/ip2location_ruby/database_config.rb",
    "lib/ip2location_ruby/i2l_float_data.rb",
    "lib/ip2location_ruby/i2l_ip_data.rb",
    "lib/ip2location_ruby/i2l_string_data.rb",
    "lib/ip2location_ruby/ip2location_config.rb",
    "lib/ip2location_ruby/ip2location_record.rb",
    "spec/assets/DB24.DEMO4.BIN",
    "spec/assets/DB24.DEMO6.BIN",
    "spec/assets/IP-COUNTRY-SAMPLE.BIN",
    "spec/ip2location_ruby_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/ip2location/ip2location-ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.1"
  s.summary = "the ip2location ruby library"

  if s.respond_to?(:metadata=)
    s.metadata = {
      "bug_tracker_uri" => "https://github.com/ip2location/ip2location-ruby/issues",
      "homepage_uri" => "https://www.ip2location.com",
      "source_code_uri" => "https://github.com/ip2location/ip2location-ruby",
    }
  end

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bindata>, [">= 0"])
      s.add_development_dependency(%q<awesome_print>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<bindata>, [">= 0"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bindata>, [">= 0"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

